spring.application.name=backend

# Base de données PostgreSQL
# URL de connexion au conteneur Docker exposé sur le port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=hospital_user
spring.datasource.password=hospital_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
# Affiche les requêtes SQL dans la console pour faciliter le débogage
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update