spring.application.name=backend

# Base de données PostgreSQL
# URL de connexion au conteneur Docker exposé sur le port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=hospital_user
spring.datasource.password=hospital_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
# Synchronisation automatique du schéma de la BD
spring.jpa.hibernate.ddl-auto=update
# Désactive l'Open Session In View pour une meilleure gestion transactionnelle
spring.jpa.open-in-view=false
# Affiche les requêtes SQL formatées dans la console en phase de dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
